In [1]:
import zipfile
import os

zip_path = r'C:\Users\fprado\Downloads\cloud_provider_challenge_dataset_v1 (1).zip'
extract_dir = r'C:\Users\fprado\Desktop\Mineria 2\extracted_data'

# Create the extraction directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print(f"Archivo '{zip_path}' descomprimido en '{extract_dir}'")

# List contents of the extracted directory
print("Contenido del directorio extraído:")
for root, dirs, files in os.walk(extract_dir):
    for name in files:
        print(os.path.join(root, name))
    for name in dirs:
        print(os.path.join(root, name))

Archivo 'C:\Users\fprado\Downloads\cloud_provider_challenge_dataset_v1 (1).zip' descomprimido en 'C:\Users\fprado\Desktop\Mineria 2\extracted_data'
Contenido del directorio extraído:
C:\Users\fprado\Desktop\Mineria 2\extracted_data\README.txt
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\billing_monthly.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\customers_orgs.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\marketing_touches.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\nps_surveys.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\resources.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\support_tickets.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\users.csv
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0000.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0001.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0002.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0003.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0004.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0005.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0006.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0007.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0008.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0009.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0010.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0011.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0012.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0013.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0014.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0015.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0016.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0017.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0018.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0019.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0020.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0021.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0022.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0023.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0024.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0025.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0026.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0027.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0028.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0029.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0030.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0031.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0032.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0033.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0034.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0035.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0036.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0037.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0038.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0039.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0040.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0041.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0042.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0043.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0044.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0045.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0046.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0047.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0048.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0049.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0050.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0051.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0052.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0053.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0054.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0055.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0056.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0057.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0058.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0059.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0060.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0061.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0062.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0063.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0064.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0065.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0066.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0067.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0068.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0069.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0070.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0071.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0072.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0073.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0074.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0075.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0076.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0077.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0078.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0079.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0080.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0081.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0082.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0083.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0084.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0085.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0086.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0087.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0088.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0089.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0090.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0091.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0092.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0093.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0094.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0095.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0096.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0097.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0098.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0099.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0100.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0101.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0102.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0103.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0104.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0105.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0106.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0107.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0108.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0109.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0110.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0111.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0112.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0113.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0114.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0115.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0116.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0117.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0118.jsonl
C:\Users\fprado\Desktop\Mineria 2\extracted_data\datalake\landing\usage_events_stream\events_part_0119.jsonl

In [2]:
import os
import pandas as pd

data_frames = {}
landing_dir = extract_dir + '/datalake/landing'

# List all files in the landing directory
for filename in os.listdir(landing_dir):
    if filename.endswith('.csv'):
        filepath = os.path.join(landing_dir, filename)
        # Create a DataFrame name based on the filename (e.g., df_customers_orgs)
        df_name = 'df_' + filename.replace('.csv', '')
        data_frames[df_name] = pd.read_csv(filepath)

Todas las tablas CSV se han cargado ahora en un diccionario llamado `data_frames`. Cada clave en este diccionario es el nombre de un DataFrame (por ejemplo, `df_customers_orgs`) y su valor es el DataFrame de pandas correspondiente. Puedes ver todas las tablas cargadas listando las claves del diccionario:

In [3]:
# Listar todas las claves (nombres de tablas) en el diccionario data_frames
print("Tablas cargadas en 'data_frames':", data_frames.keys())

Tablas cargadas en 'data_frames': dict_keys(['df_billing_monthly', 'df_customers_orgs', 'df_marketing_touches', 'df_nps_surveys', 'df_resources', 'df_support_tickets', 'df_users'])

In [4]:
# Acceder a una tabla específica y mostrar sus primeras filas
display(data_frames['df_customers_orgs'].head())

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
0,org_xaji0y6d,Nimbus Labs 0,Education,sa-east,standard,True,2025-05-26,rep_c,churned,partner,NaN
1,org_pbhsahxt,Nova Tech 1,Education,us-east,standard,False,2025-06-16,rep_d,lead,event,-3.0
2,org_hv3a3zmf,Gamma Data 2,Media,eu-central,pro,True,2025-05-12,rep_c,active,organic,4.0
3,org_8mdd4v30,Apex Data 3,Manufacturing,sa-east,standard,False,2025-05-30,rep_b,active,ads,12.0
4,org_t9nt3w5u,Delta Digital 4,E-commerce,us-west,standard,False,2025-05-16,rep_d,active,partner,17.0

---

## Exploración Inicial: `df_customers_orgs`

In [5]:
import pandas as pd

df_name = 'df_customers_orgs'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_customers_orgs

--- HEAD ---

,org_id,org_name,industry,hq_region,plan_tier,is_enterprise,signup_date,sales_rep,lifecycle_stage,marketing_source,nps_score
0,org_xaji0y6d,Nimbus Labs 0,Education,sa-east,standard,True,2025-05-26,rep_c,churned,partner,NaN
1,org_pbhsahxt,Nova Tech 1,Education,us-east,standard,False,2025-06-16,rep_d,lead,event,-3.0
2,org_hv3a3zmf,Gamma Data 2,Media,eu-central,pro,True,2025-05-12,rep_c,active,organic,4.0
3,org_8mdd4v30,Apex Data 3,Manufacturing,sa-east,standard,False,2025-05-30,rep_b,active,ads,12.0
4,org_t9nt3w5u,Delta Digital 4,E-commerce,us-west,standard,False,2025-05-16,rep_d,active,partner,17.0

--- SHAPE ---

Filas: 80, Columnas: 11

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   org_id            80 non-null     object
 1   org_name          80 non-null     object
 2   industry          80 non-null     object
 3   hq_region         80 non-null     object
 4   plan_tier         80 non-null     object
 5   is_enterprise     80 non-null     bool
 6   signup_date       80 non-null     object
 7   sales_rep         80 non-null     object
 8   lifecycle_stage   80 non-null     object
 9   marketing_source  80 non-null     object
 10  nps_score         69 non-null     float64
dtypes: bool(1), float64(1), object(9)
memory usage: 6.5+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

        nps_score
count   69.000000
mean    18.666667
std     26.071546
min    -38.000000
25%      1.000000
50%     14.000000
75%     34.000000
max    101.000000

--- VALORES NULOS ---

           Total Nulos  Porcentaje Nulos
nps_score           11             13.75

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_name ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: industry ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 10
Valores más frecuentes (Top 5):

industry
Gaming           12
Education        10
Manufacturing    10
Government        9
Retail            9
Name: count, dtype: int64

--- Columna: hq_region ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 7
Valores más frecuentes (Top 5):

hq_region
eu-central      16
ap-south        15
us-east         14
ap-northeast    11
sa-east         10
Name: count, dtype: int64

--- Columna: plan_tier ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 4
Valores más frecuentes (Top 5):

plan_tier
standard      41
pro           21
enterprise    10
free           8
Name: count, dtype: int64

--- Columna: is_enterprise ---
Tipo de dato: bool
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: False
Máximo: True
Media: 0.21
Desviación estándar: 0.41

--- Columna: signup_date ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 40
Valores más frecuentes (Top 5):

signup_date
2025-05-26    4
2025-05-29    4
2025-06-19    4
2025-06-03    4
2025-05-10    3
Name: count, dtype: int64

--- Columna: sales_rep ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 5
Valores más frecuentes (Top 5):

sales_rep
rep_d    22
rep_b    18
rep_e    17
rep_a    14
rep_c     9
Name: count, dtype: int64

--- Columna: lifecycle_stage ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 5
Valores más frecuentes (Top 5):

lifecycle_stage
active      54
at_risk     11
churned      6
prospect     6
lead         3
Name: count, dtype: int64

--- Columna: marketing_source ---
Tipo de dato: object
Valores no nulos: 80
Valores nulos: 0 (0.00%)
Número de valores únicos: 5
Valores más frecuentes (Top 5):

marketing_source
event       21
organic     17
partner     16
ads         14
referral    12
Name: count, dtype: int64

--- Columna: nps_score ---
Tipo de dato: float64
Valores no nulos: 69
Valores nulos: 11 (13.75%)
Número de valores únicos: 45
Mínimo: -38.0
Máximo: 101.0
Media: 18.67
Desviación estándar: 26.07

=======================================================

## Exploración Inicial: `df_support_tickets`

In [6]:
import pandas as pd

df_name = 'df_support_tickets'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_support_tickets

--- HEAD ---

,ticket_id,org_id,category,severity,created_at,resolved_at,csat,sla_breached
0,tkt_zjrumxqw,org_x7eedtjv,performance,low,2025-07-02,2025-07-08,4.0,False
1,tkt_3b4nthzm,org_gv0e38da,security,low,2025-07-21,2025-07-22,NaN,False
2,tkt_32hzs32d,org_9mx2x18h,availability,low,2025-07-03,2025-07-05,3.0,False
3,tkt_1jqbexgf,org_1swjckjl,usability,critical,2025-07-18,2025-07-22,4.0,False
4,tkt_vnnvbzw5,org_trp0j43d,integration,low,2025-07-26,2025-07-31,3.0,False

--- SHAPE ---

Filas: 1000, Columnas: 8

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ticket_id     1000 non-null   object
 1   org_id        1000 non-null   object
 2   category      1000 non-null   object
 3   severity      1000 non-null   object
 4   created_at    1000 non-null   object
 5   resolved_at   760 non-null    object
 6   csat          746 non-null    float64
 7   sla_breached  1000 non-null   bool
dtypes: bool(1), float64(1), object(6)
memory usage: 55.8+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

             csat
count  746.000000
mean     3.301609
std      1.260200
min      0.000000
25%      3.000000
50%      3.000000
75%      4.000000
max      7.000000

--- VALORES NULOS ---

             Total Nulos  Porcentaje Nulos
csat                 254              25.4
resolved_at          240              24.0

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: ticket_id ---
Tipo de dato: object
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 1000
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: category ---
Tipo de dato: object
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

category
integration     181
billing         180
availability    165
usability       161
performance     158
Name: count, dtype: int64

--- Columna: severity ---
Tipo de dato: object
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 4
Valores más frecuentes (Top 5):

severity
low         412
medium      328
high        204
critical     56
Name: count, dtype: int64

--- Columna: created_at ---
Tipo de dato: object
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 115
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: resolved_at ---
Tipo de dato: object
Valores no nulos: 760
Valores nulos: 240 (24.00%)
Número de valores únicos: 125
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: csat ---
Tipo de dato: float64
Valores no nulos: 746
Valores nulos: 254 (25.40%)
Número de valores únicos: 8
Mínimo: 0.0
Máximo: 7.0
Media: 3.30
Desviación estándar: 1.26

--- Columna: sla_breached ---
Tipo de dato: bool
Valores no nulos: 1000
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: False
Máximo: True
Media: 0.10
Desviación estándar: 0.29

=======================================================

## Exploración Inicial: `df_users`

In [7]:
import pandas as pd

df_name = 'df_users'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_users

--- HEAD ---

,user_id,org_id,email,role,active,created_at,last_login
0,user_9tze5r5u,org_3t60rjiw,user_9tze5r5u@example.com,devops,True,2025-07-10,NaN
1,user_qpgb7r3o,org_afeyuhz1,user_qpgb7r3o@example.com,developer,True,2025-07-15,2025-08-10
2,user_cwbfuk9e,org_ykl1cq99,user_cwbfuk9e@example.com,developer,True,2025-06-12,2025-07-26
3,user_1v2isqp4,org_g8sbi4q2,user_1v2isqp4@example.com,developer,False,2025-05-12,NaN
4,user_9kwv08hh,org_pht0hl9x,user_9kwv08hh@example.com,ml_engineer,True,2025-08-01,2025-08-11

--- SHAPE ---

Filas: 800, Columnas: 7

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     800 non-null    object
 1   org_id      800 non-null    object
 2   email       800 non-null    object
 3   role        800 non-null    object
 4   active      800 non-null    bool
 5   created_at  800 non-null    object
 6   last_login  661 non-null    object
dtypes: bool(1), object(6)
memory usage: 38.4+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

,user_id,org_id,email,role,active,created_at,last_login
count,800,800,800,800,800,800,661
unique,800,80,800,6,2,100,110
top,user_9tze5r5u,org_0lzjjege,user_9tze5r5u@example.com,data_engineer,True,2025-05-28,2025-06-26
freq,1,19,1,201,728,16,15

--- VALORES NULOS ---

            Total Nulos  Porcentaje Nulos
last_login          139            17.375

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: user_id ---
Tipo de dato: object
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 800
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: email ---
Tipo de dato: object
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 800
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: role ---
Tipo de dato: object
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

role
data_engineer    201
devops           162
developer        130
analyst          113
ml_engineer      105
Name: count, dtype: int64

--- Columna: active ---
Tipo de dato: bool
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: False
Máximo: True
Media: 0.91
Desviación estándar: 0.29

--- Columna: created_at ---
Tipo de dato: object
Valores no nulos: 800
Valores nulos: 0 (0.00%)
Número de valores únicos: 100
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: last_login ---
Tipo de dato: object
Valores no nulos: 661
Valores nulos: 139 (17.38%)
Número de valores únicos: 110
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

=======================================================

## Exploración Inicial: `df_marketing_touches`

In [8]:
import pandas as pd

df_name = 'df_marketing_touches'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_marketing_touches

--- HEAD ---

,touch_id,org_id,campaign,channel,timestamp,clicked,converted
0,mkt_7322hr5s,org_zbikcidk,security_week,ads,2025-08-26,False,False
1,mkt_osc0whs1,org_5iqvnb4g,webinar_finops,email,2025-07-23,False,False
2,mkt_4eci9rtj,org_okep7y6w,security_week,email,2025-06-21,False,True
3,mkt_6u5a2x54,org_ohp6vz41,security_week,in_app,2025-08-09,True,False
4,mkt_u44qunf5,org_c11ertj5,upgrade_enterprise,email,2025-07-28,True,False

--- SHAPE ---

Filas: 1500, Columnas: 7

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   touch_id   1500 non-null   object
 1   org_id     1500 non-null   object
 2   campaign   1500 non-null   object
 3   channel    1500 non-null   object
 4   timestamp  1500 non-null   object
 5   clicked    1500 non-null   bool
 6   converted  1500 non-null   bool
dtypes: bool(2), object(5)
memory usage: 61.7+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

,touch_id,org_id,campaign,channel,timestamp,clicked,converted
count,1500,1500,1500,1500,1500,1500,1500
unique,1500,80,6,4,120,2,2
top,mkt_7322hr5s,org_pvs7hzio,upgrade_enterprise,event,2025-06-13,False,False
freq,1,32,271,401,23,1047,1356

--- VALORES NULOS ---

Empty DataFrame
Columns: [Total Nulos, Porcentaje Nulos]
Index: []

No hay valores nulos en esta tabla.

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: touch_id ---
Tipo de dato: object
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 1500
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: campaign ---
Tipo de dato: object
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

campaign
upgrade_enterprise    271
webinar_finops        263
genai_launch          252
welcome               247
upgrade_pro           245
Name: count, dtype: int64

--- Columna: channel ---
Tipo de dato: object
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 4
Valores más frecuentes (Top 5):

channel
event     401
email     385
ads       358
in_app    356
Name: count, dtype: int64

--- Columna: timestamp ---
Tipo de dato: object
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 120
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: clicked ---
Tipo de dato: bool
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: False
Máximo: True
Media: 0.30
Desviación estándar: 0.46

--- Columna: converted ---
Tipo de dato: bool
Valores no nulos: 1500
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: False
Máximo: True
Media: 0.10
Desviación estándar: 0.29

=======================================================

## Exploración Inicial: `df_resources`

In [9]:
import pandas as pd

df_name = 'df_resources'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_resources

--- HEAD ---

,resource_id,org_id,service,region,created_at,state,tags_json
0,res_eubfn9kr,org_pnsm43d8,compute,sa-east,2025-08-14,running,"[""env:prod""]"
1,res_fvb66h3r,org_i7p5tb94,database,ap-south,2025-06-05,stopped,NaN
2,res_cbrlqmn4,org_d14ve92m,storage,eu-central,2025-08-10,running,"[""env:prod"", ""pii:true""]"
3,res_ew1yf0dw,org_pja1wj0t,networking,us-west,2025-06-02,running,"[""pii:true""]"
4,res_n6mbypjd,org_pja1wj0t,storage,us-west,2025-06-05,running,"[""env:prod"", ""costcenter:beta""]"

--- SHAPE ---

Filas: 400, Columnas: 7

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   resource_id  400 non-null    object
 1   org_id       400 non-null    object
 2   service      400 non-null    object
 3   region       400 non-null    object
 4   created_at   400 non-null    object
 5   state        400 non-null    object
 6   tags_json    317 non-null    object
dtypes: object(7)
memory usage: 22.0+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

,resource_id,org_id,service,region,created_at,state,tags_json
count,400,400,400,400,400,400,317
unique,400,80,6,7,106,3,159
top,res_eubfn9kr,org_kdgigatj,compute,ap-northeast,2025-07-25,running,"[""team:ml""]"
freq,1,11,116,72,8,242,17

--- VALORES NULOS ---

           Total Nulos  Porcentaje Nulos
tags_json           83             20.75

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: resource_id ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 400
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: service ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

service
compute       116
storage        71
database       68
networking     64
analytics      42
Name: count, dtype: int64

--- Columna: region ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 7
Valores más frecuentes (Top 5):

region
ap-northeast    72
us-east         69
us-west         61
sa-east         57
ap-south        55
Name: count, dtype: int64

--- Columna: created_at ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 106
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: state ---
Tipo de dato: object
Valores no nulos: 400
Valores nulos: 0 (0.00%)
Número de valores únicos: 3
Valores más frecuentes (Top 5):

state
running       242
stopped       119
terminated     39
Name: count, dtype: int64

--- Columna: tags_json ---
Tipo de dato: object
Valores no nulos: 317
Valores nulos: 83 (20.75%)
Número de valores únicos: 159
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

=======================================================

## Exploración Inicial: `df_nps_surveys`

In [10]:
import pandas as pd

df_name = 'df_nps_surveys'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_nps_surveys

--- HEAD ---

         org_id survey_date  nps_score              comment
0  org_xaji0y6d  2025-08-22       11.0      Complex billing
1  org_hv3a3zmf  2025-06-13        6.0      Complex billing
2  org_hv3a3zmf  2025-06-18       15.0  Love genAI features
3  org_8mdd4v30  2025-05-24       19.0     Missing features
4  org_8mdd4v30  2025-08-26       47.0  Love genAI features

--- SHAPE ---

Filas: 92, Columnas: 4

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   org_id       92 non-null     object
 1   survey_date  92 non-null     object
 2   nps_score    73 non-null     float64
 3   comment      82 non-null     object
dtypes: float64(1), object(3)
memory usage: 3.0+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

       nps_score
count  73.000000
mean   26.164384
std    15.893756
min   -16.000000
25%    17.000000
50%    25.000000
75%    36.000000
max    68.000000

--- VALORES NULOS ---

           Total Nulos  Porcentaje Nulos
nps_score           19         20.652174
comment             10         10.869565

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 92
Valores nulos: 0 (0.00%)
Número de valores únicos: 60
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: survey_date ---
Tipo de dato: object
Valores no nulos: 92
Valores nulos: 0 (0.00%)
Número de valores únicos: 57
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: nps_score ---
Tipo de dato: float64
Valores no nulos: 73
Valores nulos: 19 (20.65%)
Número de valores únicos: 41
Mínimo: -16.0
Máximo: 68.0
Media: 26.16
Desviación estándar: 15.89

--- Columna: comment ---
Tipo de dato: object
Valores no nulos: 82
Valores nulos: 10 (10.87%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

comment
Missing features       20
Love genAI features    14
Complex billing        13
Stable but slow        13
Too expensive          12
Name: count, dtype: int64

=======================================================

## Exploración Inicial: `df_billing_monthly`

In [11]:
import pandas as pd

df_name = 'df_billing_monthly'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_billing_monthly

--- HEAD ---

,invoice_id,org_id,month,subtotal,credits,taxes,currency,exchange_rate_to_usd
0,inv_nym31sk0,org_xaji0y6d,2025-06-01,1133.34,NaN,238.00,USD,0.97684
1,inv_540sejok,org_xaji0y6d,2025-07-01,619.17,NaN,130.03,USD,1.00331
2,inv_ilp4vn2v,org_xaji0y6d,2025-08-01,540.79,NaN,113.57,ARS,0.00160
3,inv_27nls4sz,org_pbhsahxt,2025-06-01,520.91,NaN,109.39,ARS,0.00147
4,inv_xq1k1qrr,org_pbhsahxt,2025-07-01,909.56,NaN,191.01,EUR,1.09929

--- SHAPE ---

Filas: 240, Columnas: 8

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   invoice_id            240 non-null    object
 1   org_id                240 non-null    object
 2   month                 240 non-null    object
 3   subtotal              240 non-null    float64
 4   credits               103 non-null    float64
 5   taxes                 240 non-null    float64
 6   currency              240 non-null    object
 7   exchange_rate_to_usd  240 non-null    float64
dtypes: float64(4), object(4)
memory usage: 15.1+ KB

--- DESCRIBE (Estadísticas Descriptivas) ---

          subtotal     credits       taxes  exchange_rate_to_usd
count   240.000000  103.000000  240.000000            240.000000
mean    717.233583   19.099709  171.357458              0.798560
std     556.065046   19.744169   83.252273              0.418672
min   -1671.830000    0.000000   13.180000              0.001330
25%     481.825000    4.490000  110.385000              0.924432
50%     689.865000   12.600000  153.370000              0.980640
75%    1046.585000   24.465000  222.715000              1.040663
max    2237.390000   79.060000  469.850000              1.198080

--- VALORES NULOS ---

         Total Nulos  Porcentaje Nulos
credits          137         57.083333

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: invoice_id ---
Tipo de dato: object
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 240
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: month ---
Tipo de dato: object
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 3
Valores más frecuentes (Top 5):

month
2025-06-01    80
2025-07-01    80
2025-08-01    80
Name: count, dtype: int64

--- Columna: subtotal ---
Tipo de dato: float64
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 240
Mínimo: -1671.83
Máximo: 2237.39
Media: 717.23
Desviación estándar: 556.07

--- Columna: credits ---
Tipo de dato: float64
Valores no nulos: 103
Valores nulos: 137 (57.08%)
Número de valores únicos: 100
Mínimo: 0.0
Máximo: 79.06
Media: 19.10
Desviación estándar: 19.74

--- Columna: taxes ---
Tipo de dato: float64
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 240
Mínimo: 13.18
Máximo: 469.85
Media: 171.36
Desviación estándar: 83.25

--- Columna: currency ---
Tipo de dato: object
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 3
Valores más frecuentes (Top 5):

currency
USD    160
ARS     51
EUR     29
Name: count, dtype: int64

--- Columna: exchange_rate_to_usd ---
Tipo de dato: float64
Valores no nulos: 240
Valores nulos: 0 (0.00%)
Número de valores únicos: 208
Mínimo: 0.00133
Máximo: 1.19808
Media: 0.80
Desviación estándar: 0.42

=======================================================

## Exploración Inicial: `df_usage_events_stream`

In [12]:
import glob
import json

stream_dir = extract_dir + '/datalake/landing/usage_events_stream'
jsonl_files = sorted(glob.glob(stream_dir + '/*.jsonl'))
print(f"Archivos .jsonl encontrados: {len(jsonl_files)}")

registros = []
for fp in jsonl_files:
    with open(fp, 'r') as f:
        for linea in f:
            linea = linea.strip()
            if linea:
                registros.append(json.loads(linea))

data_frames['df_usage_events_stream'] = pd.DataFrame(registros)
print(f"Eventos cargados: {len(data_frames['df_usage_events_stream'])}")

Archivos .jsonl encontrados: 120
Eventos cargados: 43200

In [13]:
import pandas as pd

df_name = 'df_usage_events_stream'
df_data = data_frames[df_name]

print(f"### Exploración para: {df_name}")

print("\n--- HEAD ---\n")
display(df_data.head())

print("\n--- SHAPE ---\n")
print(f"Filas: {df_data.shape[0]}, Columnas: {df_data.shape[1]}")

print("\n--- INFO ---\n")
df_data.info()

print("\n--- DESCRIBE (Estadísticas Descriptivas) ---\n")
display(df_data.describe())

print("\n--- VALORES NULOS ---\n")
null_counts = df_data.isnull().sum()
null_percentages = (df_data.isnull().sum() / len(df_data)) * 100
null_df = pd.DataFrame({'Total Nulos': null_counts, 'Porcentaje Nulos': null_percentages})
display(null_df[null_df['Total Nulos'] > 0].sort_values(by='Porcentaje Nulos', ascending=False))
if null_df['Total Nulos'].sum() == 0:
    print("No hay valores nulos en esta tabla.")

print("\n--- VALORES DUPLICADOS ---\n")
duplicated_rows = df_data.duplicated().sum()
print(f"Número de filas duplicadas: {duplicated_rows}")
if duplicated_rows > 0:
    print("Ejemplo de filas duplicadas (primeras 5):")
    display(df_data[df_data.duplicated(keep=False)].head())

print("\n--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---\n")
for col in df_data.columns:
    print(f"\n--- Columna: {col} ---")
    print(f"Tipo de dato: {df_data[col].dtype}")
    print(f"Valores no nulos: {df_data[col].count()}")
    print(f"Valores nulos: {df_data[col].isnull().sum()} ({df_data[col].isnull().sum() / len(df_data) * 100:.2f}%)")
    print(f"Número de valores únicos: {df_data[col].nunique()}")

    if pd.api.types.is_numeric_dtype(df_data[col]):
        print(f"Mínimo: {df_data[col].min()}")
        print(f"Máximo: {df_data[col].max()}")
        print(f"Media: {df_data[col].mean():.2f}")
        print(f"Desviación estándar: {df_data[col].std():.2f}")
    elif pd.api.types.is_string_dtype(df_data[col]) or pd.api.types.is_object_dtype(df_data[col]):
        if df_data[col].nunique() < 50:
            print("Valores más frecuentes (Top 5):")
            display(df_data[col].value_counts().head(5))
        else:
            print("La columna tiene demasiados valores únicos para mostrar los más frecuentes.")
    elif pd.api.types.is_datetime64_any_dtype(df_data[col]):
        print(f"Fecha mínima: {df_data[col].min()}")
        print(f"Fecha máxima: {df_data[col].max()}")

print("\n=======================================================\n")

### Exploración para: df_usage_events_stream

--- HEAD ---

,event_id,timestamp,org_id,resource_id,service,region,metric,value,unit,cost_usd_increment,schema_version,carbon_kg,genai_tokens
0,evt_nwlh5boz2guf,2025-08-17T01:55:00Z,org_cvs4f8cg,res_i8kcmm7d,networking,sa-east,requests,None,count,0.9561,2,0.000000,NaN
1,evt_xozb632zko0g,2025-07-16T11:20:00Z,org_rixa11dp,res_nmk7yyz6,database,ap-northeast,requests,None,count,5.6521,1,NaN,NaN
2,evt_h69ugrfzcopy,2025-08-18T18:52:00Z,org_0lzjjege,res_c4t3x1hx,networking,ap-northeast,requests,124.0,count,1.4320,2,0.024800,NaN
3,evt_ccjhqux2m6uv,2025-07-29T03:32:00Z,org_nam148p0,res_83579wrr,networking,us-east,cpu_hours,3.9997,hours,0.0357,2,0.000800,NaN
4,evt_tpe5h8vn0l02,2025-08-11T15:19:00Z,org_pvs7hzio,res_jh0zagrd,networking,ap-south,cpu_hours,0.4469,hours,0.0046,2,0.000089,NaN

--- SHAPE ---

Filas: 43200, Columnas: 13

--- INFO ---

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43200 entries, 0 to 43199
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id            43200 non-null  object
 1   timestamp           43200 non-null  object
 2   org_id              43200 non-null  object
 3   resource_id         43200 non-null  object
 4   service             43200 non-null  object
 5   region              43200 non-null  object
 6   metric              43200 non-null  object
 7   value               42323 non-null  object
 8   unit                41125 non-null  object
 9   cost_usd_increment  43200 non-null  float64
 10  schema_version      43200 non-null  int64
 11  carbon_kg           32400 non-null  float64
 12  genai_tokens        3132 non-null   float64
dtypes: float64(3), int64(1), object(9)
memory usage: 4.3+ MB

--- DESCRIBE (Estadísticas Descriptivas) ---

       cost_usd_increment  schema_version     carbon_kg  genai_tokens
count        43200.000000    43200.000000  32400.000000   3132.000000
mean             3.412824        1.750000      0.011343    816.845147
std              7.923621        0.433018      0.011450    450.483307
min           -154.460800        1.000000      0.000000      0.000000
25%              0.128500        1.750000      0.000534    476.750000
50%              1.004400        2.000000      0.003386    792.000000
75%              6.117250        2.000000      0.023600   1115.500000
max            317.430800        2.000000      0.032600   2663.000000

--- VALORES NULOS ---

              Total Nulos  Porcentaje Nulos
genai_tokens        40068         92.750000
carbon_kg           10800         25.000000
unit                 2075          4.803241
value                 877          2.030093

--- VALORES DUPLICADOS ---

Número de filas duplicadas: 0

--- DICCIONARIO DE DATOS Y CONTROL DE CALIDAD POR COLUMNA ---


--- Columna: event_id ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 43200
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: timestamp ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 33953
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: org_id ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 80
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: resource_id ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 400
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: service ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 6
Valores más frecuentes (Top 5):

service
compute       12498
storage        7614
database       7419
networking     6921
analytics      4590
Name: count, dtype: int64

--- Columna: region ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 7
Valores más frecuentes (Top 5):

region
ap-northeast    7773
us-east         7566
us-west         6384
sa-east         6270
ap-south        5943
Name: count, dtype: int64

--- Columna: metric ---
Tipo de dato: object
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 3
Valores más frecuentes (Top 5):

metric
requests            19512
storage_gb_hours    12996
cpu_hours           10692
Name: count, dtype: int64

--- Columna: value ---
Tipo de dato: object
Valores no nulos: 42323
Valores nulos: 877 (2.03%)
Número de valores únicos: 19262
La columna tiene demasiados valores únicos para mostrar los más frecuentes.

--- Columna: unit ---
Tipo de dato: object
Valores no nulos: 41125
Valores nulos: 2075 (4.80%)
Número de valores únicos: 3
Valores más frecuentes (Top 5):

unit
count       18596
gb_hours    12342
hours       10187
Name: count, dtype: int64

--- Columna: cost_usd_increment ---
Tipo de dato: float64
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 25846
Mínimo: -154.4608
Máximo: 317.4308
Media: 3.41
Desviación estándar: 7.92

--- Columna: schema_version ---
Tipo de dato: int64
Valores no nulos: 43200
Valores nulos: 0 (0.00%)
Número de valores únicos: 2
Mínimo: 1
Máximo: 2
Media: 1.75
Desviación estándar: 0.43

--- Columna: carbon_kg ---
Tipo de dato: float64
Valores no nulos: 32400
Valores nulos: 10800 (25.00%)
Número de valores únicos: 4415
Mínimo: 0.0
Máximo: 0.0326
Media: 0.01
Desviación estándar: 0.01

--- Columna: genai_tokens ---
Tipo de dato: float64
Valores no nulos: 3132
Valores nulos: 40068 (92.75%)
Número de valores únicos: 1441
Mínimo: 0.0
Máximo: 2663.0
Media: 816.85
Desviación estándar: 450.48

=======================================================